### ISSUE TITLE
Git Re:初始化

### ISSUE THREAD

**Issue by fimars** [Nbsaw/vue-typescript-starter#1]
Wiki里面说的是用git clone来食用，那要不要附带说明一下清除git仓库的操作。

比如:
```zsh
rm -rf .git
git init
git remote add $giturl
# 等等
```

偷偷at一下 @Nbsaw

**Comment by yuxino** [comment]
@fimars 快下来看 ， 里面有你喜欢的喵帕斯。

// PS: 清除git仓库是什么操作(瑟瑟发抖

噢噢 知道了。因为里面混杂了我的日志。

谢谢大佬

**Comment by fimars** [comment]
@Nbsaw 可爱哭了，我的萌豚之魂在燃烧。喵帕斯！

**Comment by yuxino** [comment]
@fimars 喵帕斯!

**Comment by fimars** [comment]
close this 喵帕斯!

**Comment by yuxino** [comment]
@fimars 我发现我好像刷屏了。一直在改wiki。preview那里不行。不知道为哈图片传不上去
