### ISSUE TITLE
Wiki: Preview can't be view

### ISSUE THREAD

**Issue by fimars** [Nbsaw/vue-typescript-starter#3]
### Wiki Screenshot 
![image](https://user-images.githubusercontent.com/16299018/34099340-42071690-e41a-11e7-997e-0d2e378a9f7c.png)

### Wiki Content
```zsh
![preview](images/preview.png) # 这是什么
```

**Comment by fimars** [comment]
@Nbsaw 来这个issue, 我没搞过wiki，可以用相对路径吗? github-wiki有存图的地方吗.

**Comment by yuxino** [comment]
@fimars wiki也是一个仓库。克隆下来。旁边有个链接`https://github.com/Nbsaw/vue-typescript-starter.wiki.git`。

不知道为啥不行。可以用相对路径的,查了一下。(win的截图好丑,想套一波大佬的)

**Comment by fimars** [comment]
![image](https://user-images.githubusercontent.com/16299018/34099760-69349f8e-e41b-11e7-9022-8419219b47a1.png)

拿去~ 233

**Comment by fimars** [comment]
请求路径是这个

![image](https://user-images.githubusercontent.com/16299018/34099905-c795cd96-e41b-11e7-8a2a-251fc0f78cbe.png)

**Comment by yuxino** [comment]
@fimars 搞定了 , 赞美大佬
